### ISSUE TITLE
Cover "Wallet Apps" article

### ISSUE THREAD

**Issue by SwiftAdviser** [ton-community/ton-docs#10]
## Goal

Cover the pros & cons of the most famous wallets in the community. Help the new **user as a potential developer** decide which wallet to use and in which cases. At least we need:

* Cover pros-cons of TON Wallet extension
* Cover pros-cons of Tonkeeper
* Cover pros-cons of Tonhub

Which perspectives to cover:

1. Open-source or not?
2. Jettons support?
3. NFTs support?
4. Authorization in apps support?
5. Everyday use comfortability?

## Links

* https://www.tonspace.co/participate/wallets/apps

## Requirements

* Article must fit [Styling Guidelines](https://www.tonspace.co/contribute/guidelines#style-guide) to be accepted

**Comment by Reveloper** [comment]
I want to write this article, could you assign this to me?

**Comment by SwiftAdviser** [comment]
> I want to write this article, could you assign this to me?

Sure, you're welcome! :)
