### ISSUE TITLE
Cover "Wallet Contracts" article

### ISSUE THREAD

**Issue by SwiftAdviser** [ton-community/ton-docs#11]
## Goal

Cover which wallet contract types are in the TON Ecosystem and why they exist.

* Cover wallet contract + versions (v2,v3,v4, etc)
* Cover high-load contract
* Cover Lockup wallet contract
* Cover restricted wallet (if possible)
* Cover simple wallet contract (if possible)

## Links

* List of wallet contracts: https://github.com/ton-blockchain/ton/tree/master/crypto/smartcont
* Wallet contract versions: https://github.com/toncenter/tonweb/blob/master/src/contract/wallet/WalletSources.md
* Article: https://www.tonspace.co/participate/wallets/contracts

## Requirements

* Article must fit [Styling Guidelines](https://www.tonspace.co/contribute/guidelines#style-guide) to be accepted

**Comment by Gusarich** [comment]
Done in #31
