### ISSUE TITLE
How to integrate TON Connect 2.0 into web app

### ISSUE THREAD

**Issue by ProgramCrafter** [ton-community/ton-docs#125]
### Tutorial title

TON Connect integration

### Tutorial description

Currently, TON Connect 2.0 docs only cover its API and don't provide usage examples. I think to increase popularity of this tool a tutorial is needed.

By the end, users should be able to create an integration button in their web applications, working with any wallet supporting TON Connect 2.0 (preferably even ones that aren't ready at the moment of writing tutorial), following integration best practices.

### Tutorial tags

Web3, WebApp

### Skill level

Beginner

### Hosted on ton.org/dev, blog.ton.org, blog.ton.org or hosted elsewhere?

Hosted on ton.org/docs

**Comment by Gusarich** [comment]
I'm sure this issue should be closed now
