### ISSUE TITLE
Minter page is outdated

### ISSUE THREAD

**Issue by shaharyakir** [ton-community/ton-docs#126]
### Describe the bug

Related to #118

https://ton.org/docs/develop/dapps/tutorials/jetton-minter/

1. Tonkeeper and openmask are also supported
2. Screenshots are outdated (the tool has been redesigned)

### To reproduce

-

### Expected behavior

-

**Comment by Gusarich** [comment]
assigning @delovoyhomie as you are the author of this tutorial. Can you please fix?

**Comment by delovoyhomie** [comment]
I can update the article. @Gusarich  assign me

**Comment by delovoyhomie** [comment]
The major update has already been merged.  Implemented redesign and adding new features.

@Gusarich, can you close this issue as done?
