### ISSUE TITLE
"Payment Processing — Accepting deposits to a single wallet" from Code to Tutorial

### ISSUE THREAD

**Issue by SwiftAdviser** [ton-community/ton-docs#13]
## Goal

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/5148967/195121297-b6b8b2a8-b440-4d4c-a5fa-4a60828e48a9.png">

No one will read this example right now. It's useless. Even if we have code, we need to describe to the new developers step-by-step how it works.

## Links

* Article: https://www.tonspace.co/develop/payment-processing/deposits-single-wallet
* Source code: https://github.com/toncenter/examples/blob/main/deposits-single-wallet.js

## Requirements

* Article must fit [Styling Guidelines](https://www.tonspace.co/contribute/guidelines) to be accepted

**Comment by LevZed** [comment]
Ready!
