### ISSUE TITLE
"Payments Processing — withdrawal processing" from Code to Tutorial

### ISSUE THREAD

**Issue by SwiftAdviser** [ton-community/ton-docs#15]
## Goal

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/5148967/195121933-6119b98f-74c8-48c8-b6a4-1f8ad85047a6.png">

No one will read this example right now. It's useless. Even if we have code, we need to describe to the new developers step-by-step how it works.

## Links

* Article: https://www.tonspace.co/develop/payment-processing/withdrawals
* Source code: https://github.com/toncenter/examples/blob/main/withdrawals.js

## Requirements

* Article must fit [Styling Guidelines](https://www.tonspace.co/contribute/guidelines) to be accepted

**Comment by Aishika3** [comment]
I will try
