### ISSUE TITLE
Add how to enter test mode on Tonkeeper in the tutorial

### ISSUE THREAD

**Issue by sailor95** [ton-community/ton-docs#170]
### Is your feature request related to a problem? Please describe.

In current tutorial there's no description about how to enter test mode on Tonkeeper and the link of it is out of context.

### Describe the solution you'd like

Update section description of [prepare-a-wallet](https://ton.org/docs/develop/onboarding-challenge#prepare-a-wallet) together with screenshot.

### Describe alternatives you've considered

Have Tonkeeper team to add the method on their official doc and add a link to it.

**Comment by reveloper** [comment]
Added more details about Tonkeeper switching to testnet.
