### ISSUE TITLE
Update endpoint for TON Onboarding Challenge

### ISSUE THREAD

**Issue by reveloper** [ton-community/ton-docs#179]
### Goal

Update TON Onboarding Challenge

### Details

[TON Onboarding Challenge](https://ton.org/docs/develop/onboarding-challenge) - is a tutorial, that tells how to make blockchain transactions using JavaScript.

Need to update in [git ](https://github.com/ton-community/ton-onboarding-challenge) and [tutorial *.md](https://github.com/ton-community/ton-docs/blob/main/docs/develop/onboarding-challenge.mdx) files the TON API endpoint from `Toncenter` to Orbs [ton-access](https://www.orbs.com/ton-access/)

### Skill level

Beginner

**Comment by 1Realdevine** [comment]
#171

**Comment by 1Realdevine** [comment]
Thank you for your contributions in ton development

**Comment by reveloper** [comment]
Updated with [PR#255](https://github.com/ton-community/ton-docs/pull/255)
