### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by howardpen9** [ton-community/ton-docs#189]
### Describe the bug

The URL in https://ton.org/docs/develop/howto/compile#storage-daemon is outdated. Please fix.

![image](https://user-images.githubusercontent.com/36764495/224458875-04c010ed-161f-4ba7-a368-86812e3f8b6d.png)

### To reproduce

1. Go to https://ton.org/docs/develop/howto/compile#storage-daemon
2. Click on https://github.com/ton-blockchain/ton/blob/c00302ced4bc4bf1ee0efd672e7c91e457652430
3. Scroll down to '...'

### Expected behavior

There should be more content about Storage

**Comment by 1Realdevine** [comment]
https://github.com/ton-community/ton-docs/blob/4301c7ddddb829ef969a07f300cbfb6c9ef6746b/CONTRIBUTING.md#thank-you-for-your-interest-in-contributing

**Comment by 1Realdevine** [comment]
https://github.com/ton-community/ton-docs/blob/4301c7ddddb829ef969a07f300cbfb6c9ef6746b/CONTRIBUTING.md#-----contributing-to-ton-documentation

**Comment by 1Realdevine** [comment]
#189

**Comment by Gusarich** [comment]
@howardpen9 I'm not getting any errors. are you sure it is outdated?

**Comment by reveloper** [comment]
Thank you for your request, link to the commit 401 is fixed in the weekly update.
