### ISSUE TITLE
Tutorial - Mint a Fungible Token (Jetton)

### ISSUE THREAD

**Issue by SwiftAdviser** [ton-community/ton-docs#2]
## Goal

Cover the process of minting a fungible token on TON for new developers in the ecosystem.

Goals are:
* Describe Jetton Deployer Contracts and how they work
* Describe Jetton Deployer WebClient and how it works
* Deploy first tokens by the user of the tutorial
* Help to see the user's token balance in his wallet

## Links

* [Jetton Deployer section
](https://www.tonspace.co/develop/getting-started#jetton-deployer--fungible-tokens)

## Requirements

* Tutorial must fit [Tutorial Styling Guidelines](https://www.tonspace.co/contribute/guidelines) to be accepted

**Comment by delovoyhomie** [comment]
I do this task

**Comment by delovoyhomie** [comment]
Done in PR: https://github.com/ton-community/ton-docs/pull/34
