### ISSUE TITLE
Tutorial — Your First Telegram WebApp

### ISSUE THREAD

**Issue by SwiftAdviser** [ton-community/ton-docs#20]
## Goal

Cover the process of creating a simple _Telegram WebApp_ that retrieves some information from the TON blockchain.

Goals are:
* Describe the process of creating the bot and WebApp in Telegram
* Create a meaningful goal for the end user to be interested in finishing tutorial
* Use ready-to-use libraries for TWA ([tonstarter-twa](https://github.com/ton-defi-org/tonstarter-twa) or [twa-dev/boilerplate](https://github.com/twa-dev/Boilerplate))
* Describe the process of receiving the first information from the blockchain with one of the SDKs

## Links

* [SDKs list
](https://www.tonspace.co/develop/tools/#sdk)
* [Telegram Web Apps SDK](https://github.com/ton-defi-org/tonstarter-twa)

## Requirements

* Tutorial must fit [Tutorial Styling Guidelines](https://www.tonspace.co/contribute/guidelines) to be accepted

**Comment by maxuver** [comment]
I want to help contribute to the TON Docs. My Telegram t.me/uverpool

**Comment by patrickhoffman66** [comment]
EQB5VNF8ImI9YLhG4AlduF39QdVkteF40bWRpI9EWYUk_i6G

**Comment by Gusarich** [comment]
https://ton-community.github.io/tutorials/03-client/
