### ISSUE TITLE
Tutorial - Mint first NFT Collection

### ISSUE THREAD

**Issue by SwiftAdviser** [ton-community/ton-docs#3]
## Goal

Cover the process of minting the first NFT Collection on TON for new developers in the ecosystem.

Goals are:
* Describe NFT Standard Contracts and how to use them
* Describe one of the NFT Minters and how it works
* Deploy the first NFT to the testnet step-by-step
* Help to see the user's NFT in testnet and his wallet

## Links

* [NFT minters section
](https://www.tonspace.co/develop/getting-started#nft-minters--non-fungible-tokens)

## Requirements

* Tutorial must fit [Tutorial Styling Guidelines](https://www.tonspace.co/contribute/guidelines) to be accepted

**Comment by LevZed** [comment]
I would like to write this tutorial

**Comment by reveloper** [comment]
Done with [PR](https://github.com/ton-community/ton-docs/pull/231).
