### ISSUE TITLE
A simple step-by-step ZK project on TON

### ISSUE THREAD

**Issue by SaberDoTcodeR** [ton-community/ton-docs#302]
### Tutorial title

Simple Zero-Knowledge project on TON

### Tutorial description

In this tutorial 
* User learns about ZK and specifically ZkSnark.
* Then they write their first Circom circuit and compile it.
* Also perform MPC( Powers of TAU ceremony)Which you will be used to generate verification keys for the circuit. 
* Then they use Snarkjs library to export a func verifier of their circuit.
* They will use blueprint to deploy and write tests for the verifier.

### Tutorial tags

ZK, Zero-Knowledge, FunC, smart contracts, privacy

### Skill level

Intermediate

### Hosted on ton.org/dev, blog.ton.org, blog.ton.org or hosted elsewhere?

Hosted on ton.org/docs

**Comment by SaberDoTcodeR** [comment]
Hi,
Based on the latest [TVM upgrade](https://docs.ton.org/learn/tvm-instructions/tvm-upgrade#bls12-381), I wrote a [step-by-step tutorial](https://github.com/saberdotcoder/ton-docs) that I think can be useful for TON dev community.

Can I make a PR or should I wait for approval of the issue first?👀

**Comment by Gusarich** [comment]
@SaberDoTcodeR open the PR!
