### ISSUE TITLE
Missing explanations for bit sequences in messages serialisation

### ISSUE THREAD

**Issue by reveloper** [ton-community/ton-docs#354]
### Is your feature request related to a problem? Please describe.

The article lacks explanations for the meaning of specific bit sequences, such as 1 + 4 + 4 + 64 + 32 + 1 + 1.

### Describe the solution you'd like

Add comments or references in pages of ton.docs.org to explain the meaning of bits sequences in messages.

**Comment by Gusarich** [comment]
which article is it related to? And I'd like to complete this in any way.

**Comment by reveloper** [comment]
@Gusarich, This task involves the need to check the documentation in general for such code snippets.
[Example](https://t.me/tondev_eng/34553). It will be nice to find such places and clarify them.
