### ISSUE TITLE
Missing examples of processing ton_proof on server-side

### ISSUE THREAD

**Issue by reveloper** [ton-community/ton-docs#358]
### Is your feature request related to a problem? Please describe.

Missing examples for ton_proof.

### Describe the solution you'd like

Demo implementation or update of example for a serverside [ton_proof ](https://docs.ton.org/develop/dapps/ton-connect/sign#check-ton_proof-on-server-side)algo ([ton-connect specs](https://github.com/ton-blockchain/ton-connect/blob/main/requests-responses.md#requests-and-responses)) implemented with TS, GO, Python, .NET.
We have:
- [GO demo app](https://github.com/ton-connect/demo-dapp-backend/blob/master/proof.go) - probably ok, but need to double check step 6.
- [Python example](https://github.com/XaBbl4/pytonconnect/blob/main/examples/check_proof.py) - probably ok, but need to double check step 6.

We need:
- TS - need an example
- .NET - need an example

It will be extra useful if a server-side example demo is launchable for Mainnet and Testnet.

**Comment by reveloper** [comment]
@liketurbo, could you please make a copy of this bounty for the Rust [example](https://github.com/ton-community/ton-docs/pull/472) as for this bounty expected TS/.NET solutions. 

Also, do you have plans to cover the launchable demo part? 
You can exclude this part from bounty, if not.

**Comment by liketurbo** [comment]
> Also, do you have plans to cover the launchable demo part?

Probably not, as there is already one [ton-connect/demo-dapp-with-backend](https://github.com/ton-connect/demo-dapp-with-backend), and the [Rust example](https://github.com/liketurbo/demo-dapp-backend-rs) API is matched to work with it.

**Comment by liketurbo** [comment]
On second thought, I think it's a good idea to include the demo, as it does say "demo" in the name. So, I'm adding them for both the Rust and JS demo apps.

**Comment by WinoGarcia** [comment]
Hi, @reveloper, @liketurbo!

I have developed a [library for verifying ton_proof](https://github.com/WinoGarcia/TonProof.NET) in .NET. 
I want to add it to the documentation. There is also a [demo project](https://github.com/WinoGarcia/TonProof.NET?tab=readme-ov-file#usage) in the repository with usage examples.
