### ISSUE TITLE
Update Wallet for Devs page

### ISSUE THREAD

**Issue by reveloper** [ton-community/ton-docs#360]
### Is your feature request related to a problem? Please describe.

Information is partly outdated on the wallets apps page.

### Describe the solution you'd like

Update information about [wallets for devs](https://docs.ton.org/participate/wallets/apps) in TON Ecosystem at the moment.

**Comment by SsNiPeR1** [comment]
I think I can do it

**Comment by SwiftAdviser** [comment]
done!
