### ISSUE TITLE
Missing NFT use cases in TON Documentation

### ISSUE THREAD

**Issue by SwiftAdviser** [ton-community/ton-docs#364]
### Is your feature request related to a problem? Please describe.

The NFT Use Cases article in TON Documentation does not cover the topics of Ticket as an NFT and Authorization token as an NFT as mentioned in the provided context.

### Describe the solution you'd like

Include the topics of Ticket as an NFT and Authorization token as an NFT in the NFT Use Cases article.

**Comment by reveloper** [comment]
Completed with PR https://github.com/ton-community/ton-docs/pull/378
