### ISSUE TITLE
Add brand new explorers to the article 'Explorers in TON'

### ISSUE THREAD

**Issue by SwiftAdviser** [ton-community/ton-docs#368]
### Is your feature request related to a problem? Please describe.

The article '[Explorers in TON](https://docs.ton.org/participate/explorers)' is missing two important explorers: https://tonscan.com/ and https://ton.nftscan.com/. This information is crucial for users who want to explore the TON Blockchain.

### Describe the solution you'd like

Please update the article 'Explorers in TON' to include the following explorers:

1. [TONscan](https://tonscan.com/): This explorer provides a comprehensive view of the TON Blockchain, allowing users to search for transactions, addresses, blocks, and more.
2. [TON NFTscan](https://ton.nftscan.com/): This explorer is specifically designed for Non-Fungible Tokens (NFTs) on the TON Blockchain. It allows users to explore, track, and verify NFT transactions, contracts, and metadata.

By adding these explorers to the article, users will have access to a wider range of tools and resources to explore the TON Blockchain and its ecosystem.

**Comment by SsNiPeR1** [comment]
i will do that later today

**Comment by reveloper** [comment]
Closed with merged PR https://github.com/ton-community/ton-docs/pull/374

**Comment by reveloper** [comment]
Done.
