### ISSUE TITLE
Add highload wallet v1 and v2 SDK in the high load wallets section

### ISSUE THREAD

**Issue by SwiftAdviser** [ton-community/ton-docs#371]
### Is your feature request related to a problem? Please describe.

The [high load wallets section](https://docs.ton.org/develop/smart-contracts/tutorials/wallet#-high-load-wallets) in the documentation does not include the highload wallet v1 and v2 SDK.

### Describe the solution you'd like

Update the documentation to include the highload wallet v1 and v2 as examples in the high load wallets section:
- SDK: https://github.com/ndatg/ton-highload-wallet-contract

Created with the help of [TON Docs Wizard Bot](https://t.me/ton_docs_bot)

**Comment by awesome-doge** [comment]
- https://docs.ton.org/participate/wallets/contracts#highload-wallet-v2
- https://docs.ton.org/participate/wallets/contracts#highload-wallet-v3

Is this already done? @SwiftAdviser
