### ISSUE TITLE
Missing writing test examples for edge cases.

### ISSUE THREAD

**Issue by reveloper** [ton-community/ton-docs#381]
### Is your feature request related to a problem? Please describe.

Fireworks - is a special demo smart contract designed to facilitate hands-on learning about messages, transactions, fees, and the writing of test themes in TON.

The [fireworks-func](https://github.com/ton-community/fireworks-func) tests and [documentation](https://docs.ton.org/develop/smart-contracts/testing/writing-test-examples) lack examples of [edge cases](https://github.com/ton-community/fireworks-func/blob/main/tests/Fireworks.EdgeCases.spec.ts) and brief descriptions. 

This issue aims to help the TON Community collect various behaviors in a minimalist and clear style in one contract.

### Describe the solution you'd like

- Create a unique edge case test in the [test suite](https://github.com/ton-community/fireworks-func/blob/main/tests/Fireworks.EdgeCases.spec.ts), i.e. demonstration of the throwing [TVM error exit code](https://docs.ton.org/learn/tvm-instructions/tvm-exit-codes) or bounced message logic.
- Add valuable logic in the [smart contract](https://github.com/ton-community/fireworks-func/blob/main/contracts/fireworks.fc#L189) if it's necessary for the demonstration.
- Add a brief description in the [TON Documentation](https://docs.ton.org/develop/smart-contracts/testing/writing-test-examples).

**Comment by AnushkaPhogat16** [comment]
Hey, I'd love to work on this issue. Pls assign it to me.

**Comment by reveloper** [comment]
@AnushkaPhogat16, sure, you are welcome!

**Comment by reveloper** [comment]
@AnushkaPhogat16 how's it going?

**Comment by reveloper** [comment]
As we lost contact with the assigner @AnushkaPhogat16, I closed the issue and transferred this to [bounty](https://github.com/ton-society/grants-and-bounties/issues/360).
