### ISSUE TITLE
Add Hipo smart contracts to Smart Contracts Examples

### ISSUE THREAD

**Issue by SwiftAdviser** [ton-community/ton-docs#410]
### Is your feature request related to a problem? Please describe.

The Smart Contracts Examples article in TON Docs does not include the Hipo smart contracts.

### Describe the solution you'd like

I would like to request adding the [Hipo smart contracts](https://github.com/HipoFinance/contract) to the Smart Contracts Examples article. This will provide users with an additional example of smart contracts implemented on TON Blockchain.

**Comment by reveloper** [comment]
done
