### ISSUE TITLE
picture edit

### ISSUE THREAD

**Issue by mbaneshi** [ton-community/ton-docs#441]
### Describe the bug

[This](https://docs.ton.org/develop/data-formats/tl-b-types) page has a picture like below,It seems need some edit

<img width="1407" alt="Screen Shot 2023-12-19 at 18 45 03" src="https://github.com/ton-community/ton-docs/assets/21130612/f692eeb0-2130-4377-90a2-b1dbeffdfeba">

### To reproduce

2. Click on '...'
3. Scroll down to '...'
I provide a link on top 

### Expected behavior

The picture need some adjustment to layout properly

**Comment by reveloper** [comment]
@mbaneshi, I can't reproduce it, what is your device/browser/os?

**Comment by mbaneshi** [comment]
I will check,

**Comment by reveloper** [comment]
@mbaneshi This issue is no longer actual, right?

**Comment by mbaneshi** [comment]
No, problem exists yet.
Device : Mac middle 2014 15 inch
Browser : Google Chrome Version 121.0.6167.85 (Official Build) (x86_64)
Os : Mac Big Sur 11.7.10
![Uploading Screen Shot 2024-01-29 at 18.17.38.png…]()
