### ISSUE TITLE
[zh-Hans] crash on the tvm-instructions page

### ISSUE THREAD

**Issue by hellodword** [ton-community/ton-docs#509]
### Describe the bug

Error message in the console:

```
TypeError: c[t].toLowerCase is not a function
    at 551d2fa7.8ea067d1.js:1:11910
    at Array.filter (<anonymous>)
    at 551d2fa7.8ea067d1.js:1:11894
    at Dl (main.5c35b4ce.js:2:438168)
    at t.unstable_runWithPriority (main.5c35b4ce.js:2:492224)
    at Qa (main.5c35b4ce.js:2:378987)
    at Rl (main.5c35b4ce.js:2:437636)
    at main.5c35b4ce.js:2:437547
    at I (main.5c35b4ce.js:2:491284)
    at w.port1.onmessage (main.5c35b4ce.js:2:490007)
```

### To reproduce

1. Go to `https://docs.ton.org/zh-Hans/learn/tvm-instructions/instructions`
2. See error

### Expected behavior

won't crash

### Screenshots

![image](https://github.com/ton-community/ton-docs/assets/46193371/186b7774-1853-4b80-91a0-a9fb8b8167d1)

### Desktop (please complete the following information)

- OS: Linux
- Browser: Chromium 123.0.6312.86 / Firefox 124.0.1

**Comment by solfKwolf** [comment]
i want to fix this issue

**Comment by solfKwolf** [comment]
> > i want to fix this issue
> 
> I tried, but I must to say, the [README](https://github.com/ton-community/ton-docs/blob/533c27ec551227fc2a03884ca87a152fbef3ad53/README.md#local-default-way) won't help people to `build` or `start` [i18n things](https://github.com/ton-community/ton-docs/tree/533c27ec551227fc2a03884ca87a152fbef3ad53/i18n), maybe only the [Dockerfile](https://github.com/ton-community/ton-docs/blob/533c27ec551227fc2a03884ca87a152fbef3ad53/deployment/Docker/Dockerfile) does.

you can try this comand as fellow

```sh
npm run start -- --locale zh-Hans
``` 

finally, i submit a [pr](https://github.com/ton-community/ton-docs/pull/510) to solve this issue
