### ISSUE TITLE
Clarify what to expect after starting a full node

### ISSUE THREAD

**Issue by manelio** [ton-community/ton-docs#539]
### Is your feature request related to a problem? Please describe.

This is a common problem in all chains: one does not know what to expect after starting a node.

I have started a new full node on a server that more than meets the minimum requirements.

After one hour, status returns:

```
Local validator status: working, 1 hours
Local validator out of sync: 7 s
Local validator database size: 66.98 Gb, 34.8%.
```

The database size value is almost unchanged and the out of sync is always maintained within a few seconds.

Is this normal? Could there be a problem? Is there a rough estimate for the synchronisation time? Hours? Days? Months?

### Describe the solution you'd like

Simply provide some clarification on the information returned by status and an estimate of timing in some particular circumstances.

**Comment by awesome-doge** [comment]
https://github.com/ton-community/ton-docs/blob/3979fc896b8dfa8d54c756080cb8ddd3d3037ce0/docs/participate/run-nodes/full-node.mdx?plain=1#L207-L224
