### ISSUE TITLE
The development overview document needs to be polished

### ISSUE THREAD

**Issue by chenxin1212** [ton-community/ton-docs#578]
### Describe the bug

The order of this part should be changed to match the button order below for better intuitiveness.

<img width="727" alt="截屏2024-05-10 19 43 46" src="https://github.com/ton-community/ton-docs/assets/112388950/946b100d-f200-4a34-a27d-de2cb4fbcba2">

### To reproduce

Visit the website at https://docs.ton.org/develop/overview.

### Expected behavior

<img width="707" alt="截屏2024-05-10 19 43 56" src="https://github.com/ton-community/ton-docs/assets/112388950/33987f5f-33a7-46ac-ace8-95879ea6b5b2">

### Additional context

I will create a PR to address this issue.

**Comment by awesome-doge** [comment]
It looks like the issue has been resolved

thank you for your contribution
