### ISSUE TITLE
Single nominator pool clarification

### ISSUE THREAD

**Issue by gleb498** [ton-community/ton-docs#588]
### Is your feature request related to a problem? Please describe.

Add more clarification about what is single nominator pool and how to:

1. how to start pool
2. how to cancel pool
3. how to deposit pool
4. get pool status

### Describe the solution you'd like

Add paragraphs with

1. how to start pool
2. how to cancel pool
3. how to deposit pool
4. get pool status

instructions

**Comment by awesome-doge** [comment]
It looks like the issue has been resolved

thank you for your contribution
