### ISSUE TITLE
Make the USDT title and caution concise

### ISSUE THREAD

**Issue by gleb498** [ton-community/ton-docs#595]
### Is your feature request related to a problem? Please describe.

Need to make the USDT title and Fraud Caution concise for better reading experience 

![1](https://github.com/ton-community/ton-docs/assets/20151819/5130da25-d8d0-4476-8d70-8adccec57617)
![2](https://github.com/ton-community/ton-docs/assets/20151819/50066fbc-1536-4548-bcd3-49eb62e786d0)

### Describe the solution you'd like

Need to refactor an USDT article

**Comment by awesome-doge** [comment]
Has this issue been resolved? @gleb498

**Comment by gleb498** [comment]
> Has this issue been resolved? @gleb498

Yes. Solution is here https://github.com/ton-community/ton-docs/pull/596
