### ISSUE TITLE
Ton connect wallet

### ISSUE THREAD

**Issue by vijayflipflop** [ton-community/ton-docs#615]
### Describe the bug

when I tried to connect my wallet to Telegram the web native app beta version does not connect the wallet.

### To reproduce

2. Click on '...'
3. Scroll down to '...'

### Expected behavior

when I tried to connect my wallet to Telegram the web native app beta version does not connect the wallet.

### Screenshots

![image](https://github.com/ton-community/ton-docs/assets/104342161/b8778cf5-436e-4fd3-810e-fb3466ddf477)

**Comment by awesome-doge** [comment]
This is a docs.ton.org repo.

Your question is not related to this repo.

This problem is a problem that MiniApp developers need to solve, or it is a problem with the Mini App server.
