### ISSUE TITLE
Incorrect code sample: Retrieving Jetton wallet addresses for a given user

### ISSUE THREAD

**Issue by mahnunchik** [ton-community/ton-docs#637]
### Describe the bug

There is incorrect code sample in the section: Retrieving Jetton wallet addresses for a given user

Page: https://docs.ton.org/develop/dapps/asset-processing/jettons#retrieving-jetton-wallet-addresses-for-a-given-user

https://github.com/ton-community/ton-docs/blob/f13a069fb956aeb11a8e4863d4c42b8be2765607/docs/develop/dapps/asset-processing/jettons.md?plain=1#L111-L124

### To reproduce

* `jettonWalletAddress` is undefined
* `info` is undefined

It is not clear what means that variables

### Expected behavior

Code sample is correct

**Comment by a-bahdanau** [comment]
@reveloper Maybe close this issue?

**Comment by reveloper** [comment]
@mahnunchik thank you for report, issue was handled and example fixed.
@a-bahdanau, thank you!
