### ISSUE TITLE
Specify type of hashing algorithm for `HASHCU` and `HASHSU` instructions

### ISSUE THREAD

**Issue by novusnota** [ton-community/ton-docs#645]
### Is your feature request related to a problem? Please describe.

On [TVM Instructions](https://docs.ton.org/learn/tvm-instructions/instructions) page, there are `HASHCU` and `HASHSU` instructions, which are said to take the "representation hash" of a Cell or Slice (respectively). However, there's no description what kind of the algorithm is used for computing said hash. And as I checked, it doesn't seem to be a SHA-256 one.

### Describe the solution you'd like

A description or a reference to the algorithm used.

As of now, I've tried to peek into TON sources ([here](https://github.com/ton-blockchain/ton/blob/5c392e0f2d946877bb79a09ed35068f7b0bd333a/crypto/vm/tonops.cpp#L1210-L1211) and [there](https://github.com/ton-blockchain/ton/blob/5c392e0f2d946877bb79a09ed35068f7b0bd333a/crypto/vm/tonops.cpp#L496-L514)), but couldn't trace the code to the algorithm source. That's mostly a skill issue and a lack of CLion, but a more apt C++ developer can do this and then:

1. Improve the description in `stdlib.fc` near `cell_hash` and `slice_hash` functions
2. Improve the description on [TVM Instructions](https://docs.ton.org/learn/tvm-instructions/instructions) page for `HASHCU` and `HASHSU` instructions.

### Additional context

Original issue in tact-docs: https://github.com/tact-lang/tact-docs/issues/280

**Comment by EmelyanenkoK** [comment]
`HASHCU` and `HASHSU` basically calculate representation hash of the cell, that is equal to sha256(CellRepr(c)):
For more details check https://ton.org/tvm.pdf 3.1.5
