### ISSUE TITLE
404 Error for TON Wallet Integration Documentation URL

### ISSUE THREAD

**Issue by rrakesh28** [ton-community/ton-docs#709]
### Describe the bug

The documentation URL for the TON Wallet integration for Node.js returns a 404 Not Found error. This prevents users from accessing important integration instructions.

### To reproduce

Go to the documentation [https://docs.ton.org/develop/dapps/ton-connect/tg-bot-integration](https://docs.ton.org/develop/dapps/ton-connect/tg-bot-integration).
Observe the error message displayed.

### Expected behavior

The expected behavior is for the URL to load the relevant documentation for the TON Wallet integration for Node.js.

### Additional context

It would be helpful if the link could be updated or if alternative documentation could be provided. This issue is critical for users attempting to integrate TON Wallet with Node.js.

**Comment by reveloper** [comment]
Hello, thank you for the report! 

This guide was transfered and url have updated in result. If you faced URLs this in other pages of our documentation let us know!
