### ISSUE TITLE
Fix displays of ligatures  `≥` and `≤` for operators.

### ISSUE THREAD

**Issue by Reveloper** [ton-community/ton-docs#76]
## Goal

Need to fix ligatures for "more or equal" and "less or equal" signs.

## Proposal for updates

* Fix displays of ligatures in https://ton.org/docs articles for operators:
  - Sign `≤` should display as `<=`.
  - Sign `≥` should display as `>=`.  
* To change how it displays need to replace «\`» format to italic, for example:  «\`<=\`» need describe as  «\_<=\_»
 
  Example: _`>=a.b.c` — requires the compiler version to be higher or equal to `a.b.c`_

 * Signs `≤` and `≥` used for the description of boundary conditions should be left without changes.
 
 Example: _Stores a signed len-bit integer x into b for `0 ≤ len ≤ 257`._

## Links
* https://ton.org/docs/develop/func/compiler_directives

## Requirements
Article must fit [Styling Guidelines](https://www.tonspace.co/contribute/guidelines#style-guide) to be accepted

**Comment by delovoyhomie** [comment]
i do this task

**Comment by Sahad-09** [comment]
Hey assign this issue to me i would like to work on it

**Comment by Gusarich** [comment]
@Sahad-09 sure!
