### ISSUE TITLE
Explanation for tick-tock, merge, split on tvm_overview page

### ISSUE THREAD

**Issue by collierrgbsitisfise** [ton-community/ton-docs#79]
### Describe the bug

Would be nice to add some references/explanation for `tick-tock`, `merge`, `split` on [tvm_overview](https://github.com/ton-community/ton-docs/blame/main/docs/learn/tvm-instructions/tvm_overview.md#L17), cause it not obvious what those terms means(especially for newbies in TON like me 😅)

### To reproduce

-

### Expected behavior

-

### Screenshots

-

### Desktop (please complete the following information)

-

### Smartphone (please complete the following information)

-

### Additional context

-

**Comment by SwiftAdviser** [comment]
Thank you, it's a pretty good question! We'll cover these topics

**Comment by Gusarich** [comment]
I believe the new [Transaction Layout](https://docs.ton.org/develop/data-formats/transaction-layout#transactiondescr-types) page solves this issue.
