### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by Reveloper** [ton-community/ton-docs#91]
### Describe the bug

Jammed links on the [installation guide](https://ton.org/docs/develop/smart-contracts/environment/installation#precompiled-binaries) page.
Need to fix links for the binaries of Ubuntu 20 and Ubuntu 22.

### To reproduce

1. Go to https://ton.org/docs/develop/smart-contracts/environment/installation#precompiled-binaries
2. Click on any Ubuntu 20 or Ubuntu 22 download link.
3. See the error page

### Expected behavior

The website should show a download dialogue, and allow to download of correspondently binary files.

It works if the user refreshes the error page, but users can't figure out this and think that it's generally broken.

### Screenshots

Error page:
<img width="981" alt="Screenshot 2022-12-21 at 16 37 43" src="https://user-images.githubusercontent.com/39581753/208906759-fdf9ba9e-6e4c-4193-9198-3bc69603e465.png">

### Desktop (please complete the following information)

- macOS 12.6
- Google Chrome 
- Version 108.0.5359.124

**Comment by SwiftAdviser** [comment]
yep, fixed!
